// @generated by scripts/build-template-schema.mjs
// Source: schema/selection.v1.json

export const SELECTION_SCHEMA_VERSION = 'selection.v1' as const;
export const SELECTION_SCHEMA_PATH = 'schema/selection.v1.json' as const;

export type SelectionDeploymentTarget = 'vercel' | 'netlify' | 'railway' | 'render' | 'fly' | 'heroku' | 'aws' | 'gcp' | 'azure' | 'local';
export type SelectionDatabase = 'postgres' | 'mysql' | 'sqlite' | 'mongodb' | 'redis' | 'none';
export type SelectionStorage = 'local' | 's3' | 'cloudflare' | 'vercel-blob' | 'none';
export type SelectionAuthProvider = 'auth0' | 'clerk' | 'firebase' | 'supabase' | 'custom' | 'none';
export type SelectionPaymentProcessor = 'stripe' | 'paypal' | 'lemonsqueezy' | 'custom' | 'none';
export type SelectionAnalyticsProvider = 'google-analytics' | 'mixpanel' | 'posthog' | 'plausible' | 'custom' | 'none';
export type SelectionPackageManager = 'npm' | 'yarn' | 'pnpm' | 'bun';

export interface SelectionChoices {
  deployment_target?: SelectionDeploymentTarget;
  features?: string[];
  database?: SelectionDatabase;
  storage?: SelectionStorage;
  auth_providers?: SelectionAuthProvider[];
  payments?: SelectionPaymentProcessor;
  analytics?: SelectionAnalyticsProvider;
}

export interface SelectionDerived {
  needAuth?: boolean;
  needDb?: boolean;
  needPayments?: boolean;
  needStorage?: boolean;
}

export interface SelectionMetadata {
  name: string;
  packageManager?: SelectionPackageManager;
  createdAt?: string;
  cliVersion?: string;
}

export interface SelectionManifest {
  templateId: string;
  version: string;
  selections: SelectionChoices;
  derived?: SelectionDerived;
  metadata: SelectionMetadata;
}

