// @generated by scripts/build-template-schema.mjs
// Source: schema/selection.v1.json

export const SELECTION_SCHEMA_VERSION = 'selection.v1';
export const SELECTION_SCHEMA_PATH = 'schema/selection.v1.json';

/**
 * Choices represent user selections from dimensions (infrastructure stack choices).
 * Keys match dimension IDs from the template. Values can be single or multiple selections.
 */
export interface SelectionChoices {
  [dimensionId: string]: string | string[];
}

/**
 * Placeholders represent configuration values for template variables.
 * Keys match the placeholder registry (UPPER_SNAKE_CASE tokens).
 */
export interface SelectionPlaceholders {
  [key: string]: string | number | boolean;
}

/**
 * A complete selection manifest containing all user choices and configuration values.
 */
export interface SelectionManifest {
  schemaVersion: "1.0.0";
  templateId: string;
  timestamp?: string;
  choices: SelectionChoices;
  placeholders: SelectionPlaceholders;
}

